// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/app/dao/internal"
)

// wwwAdminRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type wwwAdminRoleDao struct {
	*internal.WwwAdminRoleDao
}

var (
	// WwwAdminRole is globally public accessible object for table www_admin_role operations.
	WwwAdminRole wwwAdminRoleDao
)

func init() {
	WwwAdminRole = wwwAdminRoleDao{
		internal.NewWwwAdminRoleDao(),
	}
}

// Fill with you ideas below.
