// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/app/dao/internal"
)

// wwwBlogDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type wwwBlogDao struct {
	*internal.WwwBlogDao
}

var (
	// WwwBlog is globally public accessible object for table www_blog operations.
	WwwBlog wwwBlogDao
)

func init() {
	WwwBlog = wwwBlogDao{
		internal.NewWwwBlogDao(),
	}
}

// Fill with you ideas below.
