// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/app/dao/internal"
)

// wwwAdminDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type wwwAdminDao struct {
	*internal.WwwAdminDao
}

var (
	// WwwAdmin is globally public accessible object for table www_admin operations.
	WwwAdmin wwwAdminDao
)

func init() {
	WwwAdmin = wwwAdminDao{
		internal.NewWwwAdminDao(),
	}
}

// Fill with you ideas below.
