// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/app/dao/internal"
)

// wwwRoleApiDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type wwwRoleApiDao struct {
	*internal.WwwRoleApiDao
}

var (
	// WwwRoleApi is globally public accessible object for table www_role_api operations.
	WwwRoleApi wwwRoleApiDao
)

func init() {
	WwwRoleApi = wwwRoleApiDao{
		internal.NewWwwRoleApiDao(),
	}
}

// Fill with you ideas below.
