// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"www.lffwl.com/app/dao/internal"
)

// wwwBlogTypeDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type wwwBlogTypeDao struct {
	*internal.WwwBlogTypeDao
}

var (
	// WwwBlogType is globally public accessible object for table www_blog_type operations.
	WwwBlogType wwwBlogTypeDao
)

func init() {
	WwwBlogType = wwwBlogTypeDao{
		internal.NewWwwBlogTypeDao(),
	}
}

// Fill with you ideas below.
