// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// WwwRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type WwwRoleDao struct {
	gmvc.M                // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      wwwRoleColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB         // DB is the raw underlying database management object.
	Table  string         // Table is the underlying table name of the DAO.
}

// WwwRoleColumns defines and stores column names for table www_role.
type wwwRoleColumns struct {
	Id        string // ID
	Name      string // 名称
	CreatedId string // 添加人
	CreatedAt string // 添加时间
	UpdatedId string // 最近更新人
	UpdatedAt string // 最近更新时间
	DeletedId string // 软删除人
	DeletedAt string // 软删除时间
}

// NewWwwRoleDao creates and returns a new DAO object for table data access.
func NewWwwRoleDao() *WwwRoleDao {
	columns := wwwRoleColumns{
		Id:        "id",
		Name:      "name",
		CreatedId: "created_id",
		CreatedAt: "created_at",
		UpdatedId: "updated_id",
		UpdatedAt: "updated_at",
		DeletedId: "deleted_id",
		DeletedAt: "deleted_at",
	}
	return &WwwRoleDao{
		C:     columns,
		M:     g.DB("default").Model("www_role").Safe(),
		DB:    g.DB("default"),
		Table: "www_role",
	}
}
