// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// WwwAdminDao is the manager for logic model data accessing and custom defined data operations functions management.
type WwwAdminDao struct {
	gmvc.M                 // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      wwwAdminColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB          // DB is the raw underlying database management object.
	Table  string          // Table is the underlying table name of the DAO.
}

// WwwAdminColumns defines and stores column names for table www_admin.
type wwwAdminColumns struct {
	Id           string //
	UserName     string // 用户名
	Password     string // 明文密码
	HashPassword string // hash密码
	CreatedId    string // 添加人
	CreatedAt    string // 添加时间
	UpdatedId    string // 最近更新人
	UpdatedAt    string // 最近更新时间
	DeletedId    string // 软删除人
	DeletedAt    string // 软删除时间
}

// NewWwwAdminDao creates and returns a new DAO object for table data access.
func NewWwwAdminDao() *WwwAdminDao {
	columns := wwwAdminColumns{
		Id:           "id",
		UserName:     "user_name",
		Password:     "password",
		HashPassword: "hash_password",
		CreatedId:    "created_id",
		CreatedAt:    "created_at",
		UpdatedId:    "updated_id",
		UpdatedAt:    "updated_at",
		DeletedId:    "deleted_id",
		DeletedAt:    "deleted_at",
	}
	return &WwwAdminDao{
		C:     columns,
		M:     g.DB("default").Model("www_admin").Safe(),
		DB:    g.DB("default"),
		Table: "www_admin",
	}
}
