// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// WwwAdminRoleDao is the manager for logic model data accessing and custom defined data operations functions management.
type WwwAdminRoleDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      wwwAdminRoleColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB              // DB is the raw underlying database management object.
	Table  string              // Table is the underlying table name of the DAO.
}

// WwwAdminRoleColumns defines and stores column names for table www_admin_role.
type wwwAdminRoleColumns struct {
	AdminId string //
	RoleId  string //
}

// NewWwwAdminRoleDao creates and returns a new DAO object for table data access.
func NewWwwAdminRoleDao() *WwwAdminRoleDao {
	columns := wwwAdminRoleColumns{
		AdminId: "admin_id",
		RoleId:  "role_id",
	}
	return &WwwAdminRoleDao{
		C:     columns,
		M:     g.DB("default").Model("www_admin_role").Safe(),
		DB:    g.DB("default"),
		Table: "www_admin_role",
	}
}
