// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// WwwRoleApiDao is the manager for logic model data accessing and custom defined data operations functions management.
type WwwRoleApiDao struct {
	gmvc.M                   // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      wwwRoleApiColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB            // DB is the raw underlying database management object.
	Table  string            // Table is the underlying table name of the DAO.
}

// WwwRoleApiColumns defines and stores column names for table www_role_api.
type wwwRoleApiColumns struct {
	ApiId  string //
	RoleId string //
}

// NewWwwRoleApiDao creates and returns a new DAO object for table data access.
func NewWwwRoleApiDao() *WwwRoleApiDao {
	columns := wwwRoleApiColumns{
		ApiId:  "api_id",
		RoleId: "role_id",
	}
	return &WwwRoleApiDao{
		C:     columns,
		M:     g.DB("default").Model("www_role_api").Safe(),
		DB:    g.DB("default"),
		Table: "www_role_api",
	}
}
